ES-6690 - fixes env vars
hpi-schul-cloud/end-to-end-tests pull request #217
Opened 2020-10-26 11:13 UTC by virgilchiriac

# Description

## Links to Tickets or other pull requests

## Changes

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-30 08:06 UTC, pauljanns approved these changes

2020-10-30 08:30 UTC, yuliashikhareva approved these changes

2020-11-03 13:12 UTC, Metauriel approved these changes

2020-11-03 14:31 UTC, CeEv requested changes
scripts/ci/integration-test.travis.sh please not remove this file, otherwise master and hotfix prs will failed.

2020-11-03 18:30 UTC, merged