Task/sc 5783 edit a student
hpi-schul-cloud/end-to-end-tests pull request #227
Opened 2020-11-04 11:46 UTC by pauljanns

https://ticketsystem.hpi-schul-cloud.org/browse/SC-5783

Admin logs in, edits an existing student, saves the changes and validates that the latter was successful.

2020-11-04 12:36 UTC, d3n153 approved these changes
Fine from my side.

2020-11-04 12:45 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +const editStudentBtn = "a[title='Nutzer bearbeiten']";
single quotes ' '

2020-11-04 12:45 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +		await elementHelpers.click("a[datatest-id='edit_student_button']");
move it to -  example const variableName = 'a[datatest-id='edit_student_button']' and the use "variableName" in function, use single quotes

2020-11-04 12:45 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +	let names = await driver.$$(tableOfStudents + ' > tr');
move it to variable

2020-11-04 12:45 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +			const firstnameContainer = await nameContainer.$('td:nth-child(1)');
move it to variable

2020-11-04 12:45 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +	let names = await driver.$$(tableOfStudents + ' > tr');
move it to variable

2020-11-04 12:45 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +			const lastnameContainer = await nameContainer.$('td:nth-child(2)');
move it to variable

2020-11-04 13:31 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +	let names = await driver.$$(tableOfStudents + ' > tr');
move it to variable

2020-11-04 13:31 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +			const firstnameContainer = await nameContainer.$('td:nth-child(1)');
move it to variable

2020-11-04 13:31 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +	let names = await driver.$$(tableOfStudents + ' > tr');
move it to variable

2020-11-04 13:31 UTC, Grzesiek80 commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +			const lastnameContainer = await nameContainer.$('td:nth-child(2)');
move it to variable

2020-11-04 13:47 UTC, Grzesiek80 approved these changes

2020-11-04 14:01 UTC, alstanki requested changes

2020-11-04 14:09 UTC, pauljanns commented on step_definitions/administartion-steps.js
> +let firstname, lastname, emailAddress;
yes, since I dont want to pass them again in the methods when I already did that once. I assign them when passing them.

2020-11-04 14:10 UTC, pauljanns commented on step_definitions/administartion-steps.js
> +When(/^.*set student firstname '([^']*)', lastname '([^']*)', email '([^']*)'$/, function (
I am not creating a new student, I am editing

2020-11-04 14:11 UTC, pauljanns commented on step_definitions/administartion-steps.js
> +When(/^.*set student firstname '([^']*)', lastname '([^']*)', email '([^']*)'$/, function (
And that scenario you are referring to is not written by me.

2020-11-04 15:06 UTC, alstanki requested changes

2020-11-04 15:06 UTC, alstanki commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +const editStudentBtn = 'a[title="Nutzer bearbeiten"]';
That's not what I meant: 
```suggestion
please use
const editStudentBtn = '.table-actions .btn .fa-edit';
```

2020-11-04 15:06 UTC, alstanki commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +const editStudentBtnEN = 'a[title="Edit users"]';
Delete it

2020-11-04 15:06 UTC, alstanki commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +	await waitHelpers.waitUntilElementIsPresent(tableOfStudents);
use method: elementHelpers.getTextFromAllElements

2020-11-04 15:06 UTC, alstanki commented on page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
> +	await waitHelpers.waitUntilElementIsPresent(tableOfStudents);
elementHelpers.getTextFromAllElements

2020-11-05 09:19 UTC, alstanki approved these changes
Looks fine :)

2020-11-05 09:19 UTC, merged