Refactor waitHelpers.js
hpi-schul-cloud/end-to-end-tests pull request #330
Opened 2021-08-26 02:26 UTC by Uzaeir

# Description

## Links to Tickets or other pull requests

## Changes

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.hpi-schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-08-28 09:16 UTC, yuliashikhareva commented on step_definitions/tasks/createTask_steps.js
> +    //await TASKListPage.sortTasksLastEdited(); // Don't know what's the function of this line here? @Denis && @Yulia
I would say it is needed.

2021-08-29 13:43 UTC, yuliashikhareva commented
there were some changes in Nuxt client (e.g Feature/bc 5 completed task) so that we have to adjust the tests in one extra PR, let it successfully run, merge into main and then merge changes into this branch. It should work.

2021-08-30 08:52 UTC, yuliashikhareva requested changes

2021-08-30 08:52 UTC, yuliashikhareva commented on runtime/helpers/waitHelpers.js
> +	await element.setValue(' ' + value);
The tests do not run if we add space here. 
![Bildschirmfoto 2021-08-30 um 10 47 45](https://user-images.githubusercontent.com/49672965/131313433-625bdf7d-2455-4b81-b5c2-a4fca54a6816.png)

2021-08-30 08:53 UTC, yuliashikhareva commented
The last test runs were fine, so I think there is no need to adjust anything in waitHelper methods. This change breaks the tests.

2021-08-30 12:44 UTC, Uzaeir commented on runtime/helpers/waitHelpers.js
> +	await element.setValue(' ' + value);
> why is the space required here? for me it not seems that the error is based here when a value is truncated...

Well I saw when I run the test in my local. It fails. Here you can see the screenshot from the failed test that text is just truncated the initials. Also happened at comments and other tabs. 
![Download](https://user-images.githubusercontent.com/86830022/131340367-908ba4b8-a666-4713-b217-703584263ee8.png)
![Screenshot (14)](https://user-images.githubusercontent.com/86830022/131340881-f4e1837d-3bd0-4905-8ae0-9128a12ea472.png)
![Screenshot (15)](https://user-images.githubusercontent.com/86830022/131340885-b46419f3-5890-4d56-8cb1-7e37f87ac427.png)
![Screenshot (13)](https://user-images.githubusercontent.com/86830022/131340888-a6316a31-29c8-4567-8993-bddc0562977a.png)

2021-09-02 10:39 UTC, closed without merging