Feature/BC-182 Student task test case
hpi-schul-cloud/end-to-end-tests pull request #344
Opened 2021-09-29 09:40 UTC by Uzaeir

# Description

  Adds the test case for new task page based on nuxt client for the student.

In this test case, student login with their credentials and see the open task in the new task menu, then student will submit the task and naviagate back to the new task menu to see the updated status of the task i.e. from open to complete task.

## Links to Tickets or other pull requests

https://ticketsystem.hpi-schul-cloud.org/browse/BC-182

## Changes

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.hpi-schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-09-29 14:00 UTC, odalys-dataport submitted a review, later dismissed

2021-10-01 07:43 UTC, CeEv commented on package.json
> +		"axios": "^0.21.4",
Only a hint, for package updates it is better to do it in a additional pr. You can use npm ci instant of npm i to install the packages without updates. But the updates do not show critical, also it is fine for this pr.

2021-10-01 07:44 UTC, CeEv commented on page-objects/pages/TASKListPage.js
> +const ungradedTaskSection = "//div[@class ='v-expansion-panel']//button[@type='button']";
If you have time in daily i am interest what the effect of // is, to know it in future. :)

2021-10-01 07:47 UTC, CeEv requested changes

2021-10-01 07:47 UTC, CeEv commented on step_definitions/tasks/nuxtSubmitTask_steps.js
> +});
linter: Missing line break after last line.

2021-10-01 07:47 UTC, CeEv commented on step_definitions/tasks/submitTask_steps.js
>  });
linter: Missing line break after last line.

2021-10-05 06:42 UTC, CeEv approved these changes

2021-10-05 06:43 UTC, CeEv approved these changes

2021-10-05 07:32 UTC, merged