hotfix/room-overview
hpi-schul-cloud/end-to-end-tests pull request #418
Opened 2022-06-21 13:46 UTC by UzaeirKhan

# Description
Hotfix for Martin's PR. Tests were failing because selector were hidden in the `div`

## Links to Tickets or other pull requests

## Changes

## Deployment

## New Repos, NPM packages or vendor scripts

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2022-06-21 15:15 UTC, Loki-Afro requested changes

2022-06-21 15:15 UTC, Loki-Afro commented on page-objects/pages/TASKPage.js
> +const createTaskAndTopicBtn = "//button//span//div//span[contains(., 'Erstellen')]";
isn't that language specific now?

2022-06-21 15:15 UTC, Loki-Afro commented on step_definitions/tasks/createTask_steps.js
> +	//await TASKListPage.clickCreateTaskButtonInTheCourse();
remove dead code.

2022-06-22 06:20 UTC, UzaeirKhan commented on step_definitions/tasks/createTask_steps.js
> +	//await TASKListPage.clickCreateTaskButtonInTheCourse();
Agreed... removed

2022-06-22 06:21 UTC, UzaeirKhan commented on page-objects/pages/TASKPage.js
> +const createTaskAndTopicBtn = "//button//span//div//span[contains(., 'Erstellen')]";
No, its not language specific.

2022-07-01 06:20 UTC, closed without merging