BC-6654 - Update mongo to v5
hpi-schul-cloud/end-to-end-tests pull request #453
Opened 2024-04-12 07:36 UTC by davwas

# Description

## Links to Tickets or other pull requests

## Changes

## Deployment

## New Repos, NPM packages or vendor scripts

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-04-12 15:19 UTC, bn-pass submitted a review, later dismissed

2024-04-16 07:44 UTC, mamutmk5 requested changes

2024-04-16 07:44 UTC, mamutmk5 commented on scripts/ci/fetch.github.sh
> +echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb.list
Use the right Unbuntu version for this package. 
In the github actions we use we are using [ubuntu-latest](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) as version and from the github runner page it is ubuntu 22.04 and as code name "Jammy Jellyfis" short "jammy".

```suggestion
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb.list
```

2024-04-17 10:02 UTC, wiaderwek submitted a review, later dismissed

2024-04-17 10:05 UTC, mamutmk5 approved these changes

2024-04-17 10:30 UTC, merged